CREATE OR REPLACE TRIGGER "MZ_MEMBERSHIP_D2000_TBIUR"
    BEFORE
    INSERT OR UPDATE OF STATUS, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP, COUNTRY, PHONE
    ON MZ_MEMBERSHIP
    REFERENCING NEW AS NEW OLD AS OLD
    FOR EACH ROW



Begin
   :new.adm_d2000_update_dt := sysdate;
End;


