CREATE OR REPLACE TRIGGER "MZ_MEMBER_D2000_TAIUR"
    AFTER
    INSERT OR UPDATE OF MEMBER_EXPIRATION_DT, STATUS, JOIN_AAA_DT, JOIN_CLUB_DT, SALUTATION, FIRST_NAME, MIDDLE_NAME, LAST_NAME, ASSOCIATE_ID, RENEW_METHOD_CD, EMAIL, ENTITLEMENT_START_DT, ENTITLEMENT_END_DT
    ON MZ_MEMBER
    REFERENCING NEW AS NEW OLD AS OLD
    FOR EACH ROW


Begin
   update mz_membership
   set    adm_d2000_update_dt = sysdate
   where  membership_ky   = :new.membership_ky;
End;